### PR TITLE
Add new features to Mantle and amdilc

### PR DESCRIPTION
**Pull request by Cherser-s**
Added several features to both Mantle and amdilc (includes mantle_wsi rework):
* sample and gather instructions support
* I_MAD instruction support
* UAV support
* switch case support for AMD IL
* improved vector shuffles for loading
* added grFreeMemory and grDestroyDevice
* added memory requirements and format info queries
* query pool support
* image and image view creation
* semaphores and events

### CODE REVIEW

**Comment by libcg** [comment]
Thanks for your work. That's a lot to review and merge at once, but I will go through it and cherry-pick/rework as needed. How was it tested?

**Comment by Cherser-s** [comment]
Well, the amdilc tweaks I tested by compiling spirv into AMD IL through AMDSPV (produces A LOT more extra garbage code, also produces instructions with _ext modifier), then ran through simple utility I wrote (didn't push it to the branch though), and then tested it by spirv-validator.
Please note: 
1. Descriptor set bindings for UAV resources are generated the same way as SRV resources' bindings do;
2. I forgot to add descriptor set decorators for samplers - gotta do it as well;
3. _ext instructions only support constant resource offsets - I don't know whether AMD IL spec supports resource index calculation from the register.

As for WSI, I simply launched MantleHelloTriangle example (with different "swapchain" formats supported), it is now working with tiling window managers/compositors properly - it crashed before cause of swapchain out of date error.

**Comment by Cherser-s** [comment]
Also I have absolutely no idea how to implement descriptor sets properly, especially without MUTABLE_DESCRIPTORS extension because:
1. It is allowed to specify less descriptor slots at GR_*_PIPELINE creation for remapping (for example, specify 2 descriptors when you can bind a descriptor set with 3 slots allocated), and validation layer (native) doesn't create messages for this.
2. some descriptor mappings may not be specified at pipeline creation, so we can't assume descriptor type for pipeline layout.
3. Also at pipeline creation nested descriptor set slot may be specified as GR_SLOT_UNUSED, which increase the complexity of binding nested descriptor sets
4. It is unclear whether we can bind the same descriptor slot to multiple resources in the same shader as well as that we can bind the same slot to different descriptor types in different stages (for example UAV in vertex shader and SRV in fragment shader).

I think without MUTABLE_DESCRIPTORS we need to create pipeline layouts and VkDescriptorSets the same way as DXVK does now.

**Comment by libcg** [comment]
Ok, thanks for fixing WSI, I noticed that problem as well. I'm not sure how to approach the descriptor set problem either, looks like it's gonna be a big hurdle to overcome.

I just reworked and pushed `mantle: implement GrSemaphore and GrEvent` to master. Please rebase when you get a chance.

**Comment by Cherser-s** [comment]
Why aren't you checking for DEVICE_LOST status?

**Comment by libcg** [comment]
After checking, the Mantle doc does state that this error code can be returned at any point. I will add a helper function for it to avoid adding these checks to every function.

**Comment by Cherser-s** [comment]
Ah ok, I see, but Mantle spec in some cases doesn't return the same (as in context) error status as Vulkan does.

**Comment by libcg** [comment]
I'm thinking about a macro that would only check for `VK_ERROR_DEVICE_LOST`, `VK_ERROR_OUT_OF_HOST_MEMORY` and `VK_ERROR_OUT_OF_DEVICE_MEMORY`, then early return with the appropriate Mantle error code if hit. Other error codes would need to be checked manually. How does that sound?

**Comment by Cherser-s** [comment]
Well, sounds good, I forgot where exactly these status codes differ, gotta check it out.

**Comment by Cherser-s** [comment]
Alright, I have resolved merge conflicts but you better cherry-pick commits or something like that. Also I think it would be better to check for malloc failures as well.

**Comment by libcg** [comment]
Yes, I've been working on the status handling, it's almost done. Instead of using a macro, I added a `getGrResult` function that translates Vulkan error codes to Mantle codes. It's simpler that way.

I will cherry-pick the commits one by one, no need to rebase. Thanks.

**Comment by Cherser-s** [comment]
Ok, take note when cherry-picking commits for sample, gather, SRV_RAW_LOAD, SRV_STRUCT_LOAD, UAV_RAW_LOAD, UAV_STRUCT_LOAD, you'll need to add changes from 58af793085ad4abedb75482b04791d56256def29 commit (I forgot to add resource decorators for descriptor set bindings, as well as forgot to add descriptor set decoration and binding for sampler variable declaration itself).

**Comment by libcg** [comment]
Error codes rework is pushed to `master`.

**Comment by Cherser-s** [comment]
Ok, should I change error codes logic in my commits and force push overriden commits to PR branch?

**Comment by libcg** [comment]
You can, but I'm planning to do it myself when I find some time

**Comment by Cherser-s** [comment]
I think I will replace vector variable id storage in amdilc module (will overwrite existing commits) to create type ids at initialization (just like with vec4 and scalar types)

**Comment by Cherser-s** [comment]
Alright, I overwrote the branch to support new result translation logic, also fixed decorators in appropriate commits instead of creating another commit.

**Comment by libcg** [comment]
I just reviewed the WSI commit, as far as I understand it completely bypasses the Vulkan swapchain, and instead renders to a buffer and passes the pixels to GDI. I'm not sure how that could be efficient. Unless you have a good explanation why you did it that way, I'm gonna have to skip that one.

**Comment by libcg** [comment]
Merged 0d67c7b, I removed the comment about `grSetMemoryPriority` as it was incorrect. It sets the priority for GPU memory, not system allocated memory.

**Comment by Cherser-s** [comment]
Wait, doesn't it specify the priority for GPU memory to be swapped in case of there is no free memory to allocate on GPU?

**Comment by libcg** [comment]
Yeah, I think so. We probably won't ever need to implement it as Mantle games have fairly low VRAM requirements by today's standards. The memory could be moved around by GRVK itself, it's not OS related.

**Comment by libcg** [comment]
Pushed 64c2de8 as 46b1d288

**Comment by Cherser-s** [comment]
Well, swapping GPU memory seems to be GPU driver's task and not API task: afaik gpu memory can be swapped on Windows both on Vulkan and D3Dxx (as well as Mantle). Yeah there is absolutely no need to implement it anyway.

**Comment by Cherser-s** [comment]
As for descriptor sets, I think that recent MUTABLE_DESCRIPTOR extension can be used, but it won't be possible to utilize `slotOffset` parameter properly.

**Comment by Cherser-s** [comment]
Why don't you handle resource offsets in SAMPLE instruction, some versions of generators do produce *_ext instructions for some reason.
Also isn't it more efficient to use scalar, vec2, vec3 where needed instead of vec4 types?

**Comment by libcg** [comment]
I'm keeping the scope as small as possible so the code doesn't get overly complex right away. For now I'm focusing on bringing up Star Swarm shaders.

Using smaller types might be more efficient but that's something that can be optimized later (if there's evidence that it helps with performance). Again, trying to keep it simple :+1:

I used your code as reference when implementing the sample instructions and it was extremely helpful, so thanks for that.

**Pull request closed without merging**
